### ISSUE TITLE
Use Clipboard in place of xclip

### ISSUE THREAD

**Issue by Slackadays** [binyomen/dotfiles#1]
I just found these dotfiles by searching for mentions of `xclip` on GH, and saw in https://github.com/binyomen/dotfiles/commit/060e739c98dc689c42b7b21f3aa16ad760dbfaf3 that you were specifically looking for some screenshot copying alternative so that it stays in the clipboard. My project Clipboard is like an intelligent, easier version of `xclip` in case you wanted to find a simpler solution. I hope it's a suitable alternative for you! https://github.com/Slackadays/Clipboard

**Comment by binyomen** [comment]
Huh, wild you found that commit from two hours ago lol. Thanks for the tip! I'll take that into consideration!
